use crate::biomes;


biomes!(VanillaBiomesStruct VanillaBiomes [
    BADLANDS "badlands",
    BADLANDS_PLATEAU "badlands_plateau",
    BAMBOO_JUNGLE "bamboo_jungle",
    BASALT_DELTAS "basalt_deltas", // 1.16
    BEACH "beach",
    BIRCH_FOREST "birch_forest",
    BIRCH_FOREST_HILLS "birch_forest_hills",
    COLD_OCEAN "cold_ocean",
    CRIMSON_FOREST "crimson_forest", // 1.16
    DARK_FOREST "dark_forest",
    DARK_FOREST_HILLS "dark_forest_hills",
    DEEP_COLD_OCEAN "deep_cold_ocean",
    DEEP_FROZEN_OCEAN "deep_frozen_ocean",
    DEEP_LUKEWARM_OCEAN "deep_lukewarm_ocean",
    DEEP_OCEAN "deep_ocean",
    DEEP_WARM_OCEAN "deep_warm_ocean",
    DESERT "desert",
    DESERT_HILLS "desert_hills",
    DESERT_LAKES "desert_lakes",
    DRIPSTONE_CAVES "dripstone_caves",
    END_BARRENS "end_barrens",
    END_MIDLANDS "end_midlands",
    END_HIGHLANDS "end_highlands",
    ERODED_BADLANDS "eroded_badlands",
    FLOWER_FOREST "flower_forest",
    FOREST "forest",
    FROZEN_RIVER "frozen_river",
    FROZEN_OCEAN "frozen_ocean",
    GIANT_SPRUCE_TAIGA "giant_spruce_taiga",
    GIANT_SPRUCE_TAIGA_HILLS "giant_spruce_taiga_hills",
    GIANT_TREE_TAIGA "giant_tree_taiga",
    GIANT_TREE_TAIGA_HILLS "giant_tree_taiga_hills",
    GRAVELLY_MOUNTAINS "gravelly_mountains",
    ICE_SPIKES "ice_spikes",
    JUNGLE "jungle",
    JUNGLE_HILLS "jungle_hills",
    JUNGLE_EDGE "jungle_edge",
    LUKEWARM_OCEAN "lukewarm_ocean",
    LUSH_CAVES "lush_caves", // 1.17
    MODIFIED_BADLANDS_PLATEAU "modified_badlands_plateau",
    MODIFIED_JUNGLE "modified_jungle",
    MODIFIED_JUNGLE_EDGE "modified_jungle_edge",
    MODIFIED_WOODED_BADLANDS_PLATEAU "modified_wooded_badlands_plateau",
    MODIFIED_GRAVELLY_MOUNTAINS "modified_gravelly_mountains",
    MOUNTAINS "mountains",
    MOUNTAIN_EDGE "mountain_edge",
    MUSHROOM_FIELDS "mushroom_fields",
    MUSHROOM_FIELD_SHORE "mushroom_field_shore",
    NETHER "nether", // < 1.16
    NETHER_WASTES "nether_wastes", // < 1.16
    OCEAN "ocean",
    PLAINS "plains",
    RIVER "river",
    SAVANNA "savanna",
    SAVANNA_PLATEAU "savanna_plateau",
    SHATTERED_SAVANNA "shattered_savanna",
    SHATTERED_SAVANNA_PLATEAU "shattered_savanna_plateau",
    SMALL_END_ISLANDS "small_end_islands",
    SNOWY_BEACH "snowy_beach",
    SNOWY_MOUNTAINS "snowy_mountains",
    SNOWY_TUNDRA "snowy_tundra",
    SNOWY_TAIGA "snowy_taiga",
    SNOWY_TAIGA_HILLS "snowy_taiga_hills",
    SNOWY_TAIGA_MOUNTAINS "snowy_taiga_mountains",
    SOUL_SAND_VALLEY "soul_sand_valley",
    STONE_SHORE "stone_shore",
    SUNFLOWER_PLAINS "sunflower_plains",
    SWAMP "swamp",
    SWAMP_HILLS "swamp_hills",
    TAIGA "taiga",
    TAIGA_HILLS "taiga_hills",
    TAIGA_MOUNTAINS "taiga_mountains",
    TALL_BIRCH_FOREST "tall_birch_forest",
    TALL_BIRCH_HILLS "tall_birch_hills",
    THE_END "the_end",
    THE_VOID "the_void",
    WARM_OCEAN "warm_ocean",
    WARPED_FOREST "warped_forest", // 1.16
    WOODED_BADLANDS_PLATEAU "wooded_badlands_plateau",
    WOODED_HILLS "wooded_hills",
    WOODED_MOUNTAINS "wooded_mountains"
]);
